services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - bank-microservices-network

    transactions-microservice:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: transactions-microservice
        env_file:
            - ../.env
        ports:
            - 4000:4000
        networks:
            - bank-microservices-network

networks:
    bank-microservices-network:
        driver: bridge
        external: true
