services:
    transactions-microservice:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: transactions-microservice
        env_file:
            - ../.env
        ports:
            - 4000:4000
        networks:
            - bank-microservices-network

networks:
    bank-microservices-network:
        driver: bridge
        external: true
