services:
    transactions-database:
        image: postgres:alpine
        container_name: transactions-database
        volumes:
            - transactions-database-data:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - 5432:5432
        networks:
            - transactions-network

    transactions-microservice:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: transactions-microservice
        depends_on:
            - transactions-database
        env_file:
            - ./.env
        ports:
            - 3000:3000
        networks:
            - transactions-network

networks:
    transactions-network:
        driver: bridge

volumes:
    transactions-database-data:
